### ISSUE TITLE
With...End With construct in C#

### ISSUE THREAD

**Issue by AFAgarap** [wynrar/PFcodes#2]
I'm not so sure of this "code shortener" for C#. But according to this blog: http://monkeyhacks.com/post/vb-net-with-end-with-in-c, it is the C# equivalent for With...End With of VB.NET. Perhaps you'd like to use this for instances like in your source program `Form1.cs`, `lines 109-112`. Just a suggestion. :)

**Comment by wynrar** [comment]
Thanks, i didnt know about that. That might prove useful for this project.

**Comment by AFAgarap** [comment]
You're welcome. I'm glad it could be of help. Nice job so far with the project :+1:
